### ISSUE TITLE
Hi Harshil ! I'm Nifi

### ISSUE THREAD

**Issue by Nifirs** [harshilpatel99/NMT_english2marthi#1]
Can you please provide me the 'attention' file that you have used here? 

I mean: from attention import AttentionLayer

I want the attention.py file, please help me it is urgent

**Comment by Nifirs** [comment]
Can you please provide me the 'attention' file that you have used here?

I mean: from attention import AttentionLayer

I want the attention.py file, please help me it is urgent

**Comment by Nifirs** [comment]
Can you please provide me the 'attention' file that you have used here?

I mean: from attention import AttentionLayer

I want the attention.py file, please help me it is urgent

**Comment by harshilpatel99** [comment]
Hi Nifi!

I have added attention.py file, you can now download it. Hope your issue gets solved now! :)

**Comment by harshilpatel99** [comment]
Hi Nifi!

I have added attention.py file, you can now download it. Hope your issue gets solved now! :)

**Comment by Nifirs** [comment]
Ok thanks a lot
