### ISSUE TITLE
Translating new senetences

### ISSUE THREAD

**Issue by DONKEY0xSHOT** [harshilpatel99/NMT_english2marthi#2]
Hey! Nice work :)
Could you please write a function to translate new sentences (which are not from the data at all)?
I've tried doing so myself, but had no luck.
I saw that you have a website which is doing exactly that, so I guess you have already created this function.
Thanks a lot!

**Comment by harshilpatel99** [comment]
Hey!

Thanks for writing back to me. That website has same code that's written on
the blog. Might have some minor tweaks in the model, but overall its same.
You can tweak some layers though!
